<?php

/**
 * @file
 * Paragraph columns module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

function par_accordion_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'par_accordion/accordion';
}

/**
 * Implements hook_theme().
 */
function par_accordion_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__paragraph_accordion' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__paragraph_accordion_item' => [
      'base hook' => 'paragraph',
    ],
    'field__field_paragraph_items' => [
      'base hook' => 'field',
    ],
  ];
}

function par_accordion_preprocess_paragraph(&$variables) {
  if ($variables['paragraph']->bundle() === 'paragraph_accordion') {
    $variables['accordion_id'] = $variables['paragraph']->bundle() . '-' . $variables['paragraph']->id();
  }

  if ($variables['paragraph']->bundle() === 'paragraph_accordion_item') {
    $parent = $variables['paragraph']->getParentEntity();
    if ($parent) {
      $variables['accordion_id'] = $parent->bundle() . '-' . $parent->id();
    }
  }
}