<?php

/**
 * @file
 * Paragraph columns module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

function par_accordion_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'par_accordion/accordion';
}

/**
 * Implements hook_theme().
 */
function par_accordion_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__paragraph_accordion' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__paragraph_accordion_item' => [
      'base hook' => 'paragraph',
    ],
    'field__field_paragraph_items' => [
      'base hook' => 'field',
    ],
  ];
}